#pragma once

#include "AST.h"
#include "Lexer.h"

struct ParseError {
  std::string msg;
  int line;
  int col;
};

class Parser {
public:
  Parser(std::vector<Token> toks, std::vector<ParseError>& errs);
  std::unique_ptr<Program> parseProgram();

private:
  std::vector<Token> toks_;
  size_t p_ = 0;
  std::vector<ParseError>* errs_;
  bool allowStructLit_ = true;
  // True while parsing a contract spec expression (inside a `requires`,
  // `ensures`, `invariant`, or `assert` clause). Only then are the spec-only
  // forms `old(x)`, `forall i: T in a..b implies P`, `exists ...`, and the
  // `implies` operator legal; outside a spec context they are rejected (or,
  // for `implies`, simply never appear). Set by the contract-clause parsers
  // and restored on return so the rest of the grammar is unchanged.
  bool inSpec_ = false;

  const Token& cur();
  const Token& peek(size_t off = 0);
  bool at(Tok t);
  bool accept(Tok t);
  bool expect(Tok t, const std::string& what);
  void error(const std::string& msg);


  bool atTopLevel();

  BType parseType();


  // Parses `<T: C = D, U: C2, ...>` (or returns leaving `out` empty when the
  // `<...>` is really a less-than op). On success `out` holds the rich params,
  // INCLUDING any constraints applied by a trailing `where` clause (which this
  // function also consumes  -  `where T: C, ...`). Caller then derives the cheap
  // names-only `typeParams` projection from `out`.
  void parseTypeParamsRich(std::vector<TypeParam>& out);
  // Consumes an inline `where T: ConceptName, U: ConceptName, ...` clause that
  // appears immediately after the `<...>` param list, rewriting `tparams` in
  // place so a where item overrides any inline `T: C` constraint (where-clause
  // wins). Also used by parseFunc / parseTrapHandler for the post-return-type
  // spelling of the same clause (`fn f<T>(...) -> R where T: C { ... }`).
  void applyWhereClause(std::vector<TypeParam>& tparams);


  std::vector<BType> tryParseTypeArgs(bool& ok);
  // ox:proof `isGhost` stamps FuncDecl::isGhost (T2  -  `ghost fn ...`). `isSpec` is unused
  // here because `spec fn` is its own decl kind (SpecFnDecl); kept separate so
  // the existing FuncDecl pipeline doesn't gain a degenerate no-body slot.
  std::unique_ptr<FuncDecl> parseFunc(bool isExtern = false, bool isGhost = false);
  // `export fn name(...) -> Ret { body }`  -  an Oxide fn made callable from C
  // (reverse of `extern fn`). Mirrors the `extern fn` top-level form: consume
  // `export`, expect `fn`, then reuse parseFunc(false) and stamp isExport=true.
  std::unique_ptr<FuncDecl> parseExportFn();
  // ox:proof `lemma fn name(params) requires R ensures E { body }`  -  a proof-only
  // top-level decl (like `ghost fn` but with the `lemma` prefix keyword).
  // Mirrors parseExportFn's pattern: consume `lemma`, expect `fn`, reuse
  // parseFunc(false) (with a body), then stamp isLemma=true on the returned
  // FuncDecl. The result is pushed into `prog->lemmas` (KEPT SEPARATE from
  // `funcs`, like `trapHandlers`). Lemmas are never codegen'd; the Ghost
  // encoder emits a universal axiom for each, and the SMT encoder discharges
  // the lemma's own body (the proof) like a regular fn.
  std::unique_ptr<FuncDecl> parseLemma();
  std::unique_ptr<StructDecl> parseStruct();
  std::unique_ptr<EnumDecl> parseEnum();
  std::unique_ptr<ImplDecl> parseImpl();
  // `bitfield Name: BaseType { field: bit N; field: bits A..B; ... }`  - 
  // verified bitfield DSL. Parses the surface syntax into a BitfieldDecl
  // (recorded by the caller in Program::bitfields for the Ghost encoder's
  // SMT layout axioms). The synthetic StructDecl { raw: baseType } + ImplDecl
  // (accessor/setter methods, verified contracts) are generated by
  // `lowerBitfield()` (free helper in Parser.cpp) which parseProgram calls
  // right after pushing the BitfieldDecl, so they flow through the existing
  // Sema/IRGen/Ghost pipeline for structs+impls unchanged. See AST
  // BitfieldDecl and lowerBitfield in Parser.cpp.
  std::unique_ptr<BitfieldDecl> parseBitfield();
  // Lower a parsed BitfieldDecl into a synthetic StructDecl { raw: baseType }
  // + ImplDecl (accessor/setter methods, verified contracts) pushed into
  // prog.structs / prog.impls so they share the existing Sema/IRGen/Ghost
  // pipeline for structs+impls unchanged. Free helper (not a Parser method  - 
  // it takes the Program it mutates, which parseProgram owns). Defined in
  // Parser.cpp; declared here so parseProgram can call it before its
  // definition appears later in the translation unit.
  void lowerBitfield(Program& prog, const BitfieldDecl& bf);
  std::unique_ptr<ConceptDecl> parseConceptDecl();
  std::unique_ptr<TypedefDecl> parseTypedef();
  std::unique_ptr<VarDecl> parseGlobal(bool isExtern);
  // ox:proof T1/T3 module-level decls. parseSpecFn parses `spec fn ... = expr ;` (no
  // body block); parseRegion parses `region Name = { a, b, ... };`;
  // parseRefines parses `refines <fn> <= <fn> ;`. Missing-#6 parsePreserves
  // parses `preserves <handler> <= <invariant_spec_fn> ;` (mirrors refines).
  // `ghost let` (T2) is a STATE-LEVEL production handled by parseStmt (so it
  // parses inside fn bodies and loop bodies, where ordinary lets live);
  // `ghost fn` reuses parseFunc.
  std::unique_ptr<SpecFnDecl> parseSpecFn();
  // `asm spec name(params) -> T requires ... ensures ...;`  -  hardware-
  // instruction spec declaration. Reuses SpecFnDecl (with isAsmSpec=true),
  // stored in prog->specFns so the existing collectSpecFns / c.specFns / Ghost
  // emitSpecFns path sees it unchanged. Has requires/ensures (like a FuncDecl)
  // and NO `= body`  -  the instruction's behaviour is captured by the clauses.
  // An `asm!(...) implements <name>` clause on a concrete asm block links to it.
  std::unique_ptr<SpecFnDecl> parseAsmSpecFn();
  std::unique_ptr<RegionDecl> parseRegion();
  std::unique_ptr<RefinesDecl> parseRefines();
  std::unique_ptr<PreservesDecl> parsePreserves();   // Missing-#6
  // ox:proof D8  -  `noninterference <h1>, <h2>, ... <= <invariant_spec_fn> ;` module-
  // level Owicki-Gries non-interference (stability) declaration. Takes a
  // comma-separated handler list + an invariant spec fn name. Mirrors
  // parsePreserves but with a handler list instead of a single handler.
  std::unique_ptr<NoninterferenceDecl> parseNoninterference();   // D8
  // D9 (gap #6)  -  `cycle_preserves <h1>, <h2>, ... <= <invariant_spec_fn> ;`
  // module-level VM-exit-cycle refinement declaration. Per-handler discharge
  // (vmlaunch/vmresume modelled as identity on the cycle invariant). Takes a
  // comma-separated handler list + an invariant spec fn name. Mirrors
  // parseNoninterference exactly (handler list + `<=` + spec fn name + `;`).
  std::unique_ptr<CyclePreservesDecl> parseCyclePreserves();   // D9
  // ox:proof D3  -  `axiom <expr>;` (optionally `axiom name: <expr>;`). Module-level
  // top-level SMT axiom. The body is parsed with inSpec set (via parseSpecExpr)
  // so `forall`/`exists`/`implies` are legal. See `AxiomDecl` in AST.h.
  std::unique_ptr<AxiomDecl> parseAxiom();   // D3
  // ox:unsafe fix2  -  `trap [handler] name(params) -> Ret requires ... ensures ... { body }`
  // (or `trap name(params) -> Ret;` prototype). A trap handler IS a FuncDecl
  // (reuses the whole param/contract/body pipeline); `isTrapHandler=true` is
  // stamped on the returned FuncDecl so the SMT encoder assumes its requires.
  // `withBody` is true for the `trap handler ...` form (expects `{ body }`),
  // false for the bare `trap name(...);` prototype form (expects `;`, no body).
  // Mirrors parseFunc's post-`fn` tail (name, generic params, param list,
  // `-> Ret`, contract clauses, body-or-semicolon) but without the leading
  // `fn` keyword and without virtual/override/self (trap handlers are free
  // top-level decls, not methods).
  std::unique_ptr<FuncDecl> parseTrapHandler(bool withBody);   // fix2
  // Compile-time macro declaration: `macro name(p1, p2, ...) { <body expr> }`.
  // `macro`/`expand` are reserved keywords (Tok::kw_macro / kw_expand). The
  // body is parsed as a full expression with `allowStructLit_` toggled off (a
  // struct-literal-looking `{` would end the macro body, so disable it); `$x`
  // markers become VarRef nodes named `"$x"`. Stored in `prog->macros`; Sema
  // builds the name->MacroDecl* registry at the top of `check`.
  std::unique_ptr<MacroDecl> parseMacro();   // macro/metaprogramming
  StmtPtr parseStmt();
  StmtPtr parseLetMut(bool isMut);
  StmtPtr parseIf();
  StmtPtr parseWhile();
  StmtPtr parseFor();
  StmtPtr parseMatch();
  StmtPtr parseReturn();
  // `unsafe { <stmts> }`  -  block scope where unsafe operations (raw pointer
  // deref, inline asm, extern calls, unchecked casts, calls to `unsafe fn`) are
  // permitted. Dispatched from parseStmt on `kw_unsafe` (when NOT followed by
  // `fn`  -  the `unsafe fn <name>...` top-level form is handled in parseProgram
  // by consuming `unsafe`, expecting `fn`, reusing parseFunc(false), and
  // stamping FuncDecl::isUnsafe=true, mirroring parseExportFn/parseLemma).
  // parseUnsafeBlock consumes `unsafe`, expects `{`, calls parseBlock (which
  // handles `{ ... }` itself), and packages the statements into an UnsafeBlock.
  StmtPtr parseUnsafeBlock();
  // ox:proof fixB  -  `instantiate forall k. P on ...;` guided-instantiation pragma.
  StmtPtr parseInstantiate();
  // ox:proof fixC  -  `proof that forall k: i64 in 0..N implies P(k) by induction on k:
  //   base: <expr>; step: assume <expr>; prove <expr>;` interactive-proof
  // block. Parses the theorem (a forall QuantExpr) via parseSpecExpr (inSpec
  // set so forall/implies are legal), the induction variable, then the base
  // case + the assume/prove step. Like `instantiate` this is a spec-level
  // statement; inSpec_ is saved/restored around each spec-expression parse
  // so the caller's state is untouched. See AST ProofStmt.
  StmtPtr parseProof();
  // `assume <expr>;` (non-trusted) and `trusted assume <expr>;` (trusted)  - 
  // a hypothesis assumption statement. The condition is a full spec expression
  // (parseSpecExpr with inSpec set so `forall`/`implies` work, mirroring
  // `assert`). The trusted form may carry a trailing `source "<citation>";`
  // clause parsed as a string literal. NOTE: this is the STANDALONE statement
  // form, dispatched from parseStmt; the proof block's internal `assume <IH>`
  // is parsed directly by parseProof (not via parseAssume) so the two never
  // conflict  -  parseStmt's `kw_assume` case only fires outside `proof` blocks
  // (parseProof consumes the whole `step: assume ... prove ...` itself). See
  // AST AssumeStmt.
  StmtPtr parseAssume();
  // calcD  -  `calc { <expr>; <REL> {hints;} <expr>; ... }` equational-reasoning
  // block. Each step's expression is parsed via parseSpecExpr (inSpec set so
  // `forall`/`implies` work, mirroring `assert`/`proof`); the relation token
  // (`==`/`!=`/`<=`/`>=`/`<`/`>`) and the optional `{ <hint stmts> }` block
  // come AFTER each `;`-terminated expression and BEFORE the next expression.
  // The last step has no trailing REL (just `expr ;`). Like `proof`/`instantiate`
  // this is a spec-level statement; inSpec_ is saved/restored around each
  // spec-expression parse so the caller's state is untouched. See AST CalcStmt.
  StmtPtr parseCalc();
  // Parse zero-or-more `requires <expr>` / `ensures <expr>` contract clauses
  // for a function, appending to `out_req`/`out_ens`. Only parsed for defined
  // (non-extern) functions, after the signature and before `{`. Each clause is
  // a full spec expression (inSpec is set during its parse), terminated by the
  // next `requires`/`ensures` keyword or the opening `{` (no semicolon).
  void parseFuncContracts(std::vector<ExprPtr>& out_req, std::vector<ExprPtr>& out_ens);
  // Parse zero-or-more `modifies <name1>, <name2>, ...` clauses (T3) on a fn
  // head, appending the bare names to `out`. Each occurrence is one or more
  // comma-separated identifiers (region or global/ghost-let names), terminated
  // by the next `modifies`/`requires`/`ensures` keyword or the opening `{`/`;`.
  // Multiple `modifies` entries accumulate. Only parsed for defined (non-
  // extern) functions  -  extern decls mirror a C ABI and can't carry Oxide
  // frame conditions. Empty `out` afterward means conservative default.
  void parseModifies(std::vector<std::string>& out);
  // Effect system  -  `effects { eff1, eff2, ... }` (or `effects { }`) on a fn
  // head, mirroring parseModifies's shape. Each occurrence is a brace-
  // delimited, comma-separated list of identifiers naming effects (built-in
  // like io/alloc/asm/mmio/vmcs_read/vmcs_write/mem_write/panic/trap/sched, or
  // user-defined). Empty `{ }` is accepted (means pure). May occur zero or
  // more times; each occurrence's names accumulate into `out`, deduplicated on
  // insertion in Sema. `outExplicit` is set true iff an `effects` clause was
  // actually consumed  -  used downstream to distinguish "omitted" (untracked,
  // no enforcement) from "explicitly pure" (`effects { }`, purity enforced),
  // so the propagation/purity checks and the blanket frame axiom fire ONLY
  // when the source literally wrote `effects { ... }` and never for a fn that
  // omitted the clause entirely. Consumed alongside requires/ensures/
  // modifies in the post-signature tail loop of parseFunc / parseTrapHandler.
  void parseEffects(std::vector<std::string>& out, bool& outExplicit);
  // Parse zero-or-more `invariant <expr>` clauses for a loop, before `{`.
  void parseLoopInvariants(std::vector<ExprPtr>& out);
  // Parse one contract spec expression (inSpec set), returning the Expr.
  ExprPtr parseSpecExpr();
  std::vector<StmtPtr> parseBlock();

  ExprPtr parseExpr();
  ExprPtr parseRange();
  ExprPtr parseAssign();
  ExprPtr parseTernary();
  ExprPtr makeIncDec(bool isInc, bool isPost, ExprPtr base);
  ExprPtr parseLogicOr();
  // ox:proof `implies` binds looser than `||` and is right-associative; it is only legal
  // in a contract spec (inSpec_), where it is parsed at this level. Outside a
  // spec it is never produced (parseAssign calls parseTernary directly).
  ExprPtr parseImplies();
  ExprPtr parseLogicAnd();
  ExprPtr parseBitOr();
  ExprPtr parseBitXor();
  ExprPtr parseBitAnd();
  ExprPtr parseEquality();
  ExprPtr parseRel();
  ExprPtr parseShift();
  ExprPtr parseAdd();
  ExprPtr parseMul();
  ExprPtr parseCast();
  ExprPtr parseUnary();
  // parsePower  -  right-associative power operator. Sits BETWEEN parseCast
  // and parseUnary in the precedence chain so power binds TIGHTER than unary
  // minus (`-x^2` == `-(x^2)`). Handles `Tok::pow` (`**`) building a PowerExpr
  // (`base ** exponent`). The postfix Unicode superscript forms (`²`, `³`) and
  // standalone math glyphs (`π`, `√`, `∫`) are handled in parsePostfix /
  // parsePrimary respectively (see parsePostfix's `Tok::math_sym` arm and
  // parsePrimary's `kw_*`/`math_sym` arms). Right-assoc: `2 ** 3 ** 2` == `2
  // ** (3 ** 2)`.
  ExprPtr parsePower();
  ExprPtr parsePostfix();
  ExprPtr parsePrimary();


  using PrecedenceFn = ExprPtr (Parser::*)();
};
